staffsearch/urls.py
from django.contrib import admin
from django.urls import path
import staff.views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', staff.views.index, name="index"),
    path('directory/', staff.views.directory, name="directory"),
    path('keywords/', staff.views.keyword_list, name='keywords'),
    path('search/', staff.views.index, name="index")
]

helpers/models.py
from django.db import models


class TrackingModel(models.Model):
    created_at=models.DateTimeField(auto_now_add=True)
    updated_at=models.DateTimeField(auto_now=True)

    class Meta:
        abstract=True
        ordering=('-created_at',)

staff/models.py
from django.db import models
from helpers.models import TrackingModel

class Institute(TrackingModel):
    name = models.CharField(max_length=128, unique=True)

    def __str__(self):
        return self.name

class Directorate(TrackingModel):
    name = models.CharField(max_length=128, unique=True)

    def __str__(self):
        return self.name

class Department(TrackingModel):
    name = models.CharField(max_length=256, unique=True)
    institute = models.ForeignKey(Institute, blank=True, null=True, on_delete=models.PROTECT)

    def __str__(self):
        return self.name

class Profile(TrackingModel):
    last_name = models.CharField(max_length=256)
    first_name = models.CharField(max_length=256)

    role = models.CharField(max_length=256)
    email = models.EmailField(unique=True)
    url = models.URLField()
    department = models.ForeignKey(Department, on_delete=models.PROTECT)
    about = models.TextField(blank=True, null=True)
    research = models.TextField(blank=True, null=True)
    teaching = models.TextField(blank=True, null=True)
    publications = models.TextField(blank=True, null=True)
    professional_activities = models.TextField(blank=True, null=True)
    additional_info = models.TextField(blank=True, null=True)
    visible = models.BooleanField(default=True)
    last_updated = models.DateTimeField(blank=True, null=True)

    def __str__(self):
        return self.last_name

class Keyword (TrackingModel):
    keyword = models.CharField(max_length = 128)
    score = models.FloatField(default=0)
    frequency = models.IntegerField(default=0)
    visible = models.BooleanField(default=True)

    def __str__(self):
        return self.keyword

class Banner(TrackingModel):
    url = models.URLField(default="https://github.com/rtreharne/staff-search-static/blob/main/University%20of%20Liverpool%20campus%20010621%200040.JPG?raw=true")

    def __str__(self):
        return self.url

staff/forms.py
from django import forms
from staff.models import Department

departments = Department.objects.all().order_by('name')
department_list = [(x.name, x.name) for x in departments]

class SearchForm(forms.Form):
    CHOICES = [("All Departments", "All Departments"),
               ("------------", "------------")]
    CHOICES.extend(department_list)

    CHOICES = tuple(CHOICES)

    keyword = forms.CharField(label="Search", max_length=100,
                              widget=forms.TextInput(attrs={'placeholder': "Search by keyword or surname"}))
    department = forms.ChoiceField(choices=CHOICES)

staff/views.py
from django.shortcuts import render
from staff.models import Institute, Profile, Department
from staff.forms import SearchForm
from django.contrib.postgres.search import SearchVector, SearchRank, SearchQuery
from staff.models import Profile, Department, Keyword, Banner

def get_banner():
    banner = Banner.objects.order_by('?').first()
    return banner.url


def index(request):

    context = {"banner": get_banner()}

    vector = SearchVector("last_name",
                          "first_name",
                          "role",
                          "about",
                          "research",
                          "teaching",
                          "publications",
                          "professional_activities",
                          "additional_info")

    if request.method == "POST":
        form = SearchForm(request.POST)
        if form.is_valid():

            query = SearchQuery(form.cleaned_data["keyword"])

            department = Department.objects.filter(name=form.cleaned_data["department"])

            if len(department) > 0:
                profiles = Profile.objects.filter(department=department[0])
            else:
                profiles = Profile.objects.all()

            search = profiles.annotate(rank=SearchRank(vector, query)).filter(rank__gte=0.01).order_by('-rank')

            if len(search) > 0:
                max_value = max([x.rank for x in search])
                for item in search:
                    score = item.rank*100/max_value
                    item.rank = score

            context["results"] = search
            context["keyword"] = form.cleaned_data["keyword"]
    else:
        form = SearchForm

    keyword = request.GET.get('keyword', None)
    print(keyword)
    print(request)
    if keyword:
        query = SearchQuery(keyword)
        profiles = Profile.objects.all()

        search = profiles.annotate(rank=SearchRank(vector, query)).filter(rank__gte=0.01).order_by('-rank')

        if len(search) > 0:
            max_value = max([x.rank for x in search])
            for item in search:
                score = item.rank * 100 / max_value
                item.rank = score

        context["results"] = search
        context["keyword"] = keyword
        context["form"] = form

        return render(request, "index.html", context)

    context["form"] = form

    return render(request, "index.html", context)

def directory(request):
    # get institutes
    institutes = Institute.objects.all().order_by('name')
    departments = Department.objects.all().order_by('name')
    profiles = Profile.objects.all().order_by('last_name')

    context = {'institutes': institutes,
               'departments': departments,
               'profiles': profiles,
               'banner': get_banner()}

    return render(request, "directory.html", context)

def keyword_list(request):
    # get keywords
    keywords = Keyword.objects.filter(visible=True, frequency__gte=1).order_by('-frequency')

    context = {'keywords': keywords,
               'banner': get_banner()}


    return render(request, "keywords.html", context)

staff/templates/base.html
<!DOCTYPE html>
<html>
<head>
  <title>HLS Staff Search</title>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="author" content="Robert Treharne">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
  <script type="text/javascript" src="//maxcdn.bootstrapcdn.com/bootstrap/3.3.4/js/bootstrap.min.js"></script>
  <style type="text/css">
    .container {
      font-color: #343a40 !important
    }
    #main {
      min-height: 80vh;
    }
    div#search, div#results, div#navigation div.nav{
      margin: 25px;
    }
    #id_department {
      width: 150px;
    }
    p.relevance {
      font-size: 0.8em;
    }

    label[for="id_keyword"], label[for="id_department"] {
      display: none;
    }

    .result {
      margin-top:20px;
      margin-bottom: 20px;
    }

    .result p {
      margin-bottom: 0.5rem;
    }

    select {
      height: 30px;
      border: 2px;
      margin-left: 5px;
      margin-right: 5px;

    }
    .institute-box {

    }
    .lvl1, .lvl2, .lvl3{
    cursor: pointer;
    margin-left:20px;
    }
    .department-names {
      display:none;

    }
    .department-names h4 {
      margin: 25px;
    }
    .profile-list {
      display: none;
    }
    span {
      display: block;
    }
    ul.no-bullets {
      list-style-type: none;
    }
    li.profile-listing {
      margin: 20px;
    }
    input#id_keyword {
      height: 50px;
      width: 500px;
      border-radius: 5px;
      padding-left: 15px;
    }
    #form-submit {

      display: none;
      height: 50px;



    }
    #loader {
    display: none;
    }
    .visible {
      display: visible;
    }
    .nav {
    margin-bottom: 25px;
    }
    .nav.left {
      width: 50%;
    }
    .nav.right {
      display: flex;
      margin-top: 5px;
      width: 50%;
      float: right;
      flex-direction: row-reverse;

    }
    .nav.right span {
      margin: 10px;
    }

  </style>
</head>
<body>

<div class="container" style="margin-top: 40px;">
  <div class="nav">
    <div class="nav left">
      <img src="https://www.liverpool.ac.uk/logo-size-test/full-colour.svg" style="width: 250px;">
    </div>
    <div class="nav right">
      <span><h2><a href="/">Search</a></h2></span>
      <span><h2><a href="/directory/">Directory</a></h2></span>
      <span><h2><a href="/keywords">Keywords</a></h2></span>
    </div>

    <div style="position: relative; margin: 10px; width: 100%; min-height: 300px; ">
      <img src="{{ banner }}" style="width: calc(100%); max-height: 400px; object-fit: cover;">
      <span class="overlay-text" style="position: absolute; bottom: 0px; z-index: 3; background: rgba(51, 153, 255, 0.8); width: calc(100%); padding: 15px; color: #fff "><h1 style="opacity:1">HLS Staff Search Tool</h1></span>
    </div>
  </div>

{% block content %}{% endblock %}

</div>

<footer class="containter text-center aligner">
  <div>
    &copy SoLS TEL Team 2022 </a>
  </div>
</footer>

</body>
<script>
$(function(){
    $('span').on('click', function(e){
        $(this).next('div').toggle();
    });
});
$("form").submit(function(event) {
  console.log("Hello World");
  $("#loader").get(0).style.setProperty("display", "block");
  $("#results").get(0).style.setProperty("display", "none");
});
$(".keyword").click(function(event) {
  console.log("Hello World");
  $("#loader").get(0).style.setProperty("display", "block");
  $("#results").get(0).style.setProperty("display", "none");
});
</script>
</html>

staff/templates/directory.html
{% extends "base.html" %}

{% block content %}
<div id="main" class="container">
    <div id="search">
         <h2>Directory</h2>

    </div>
    <hr>

    {% if results %}
    <div id="results">




    {% endif %}

    {% for institute in institutes %}
        <div class="institute-name lvl1">
            <span><h3>{{institute.name}}</h3></span>
            <div class="department-names lvl2">
            {% for department in departments %}
                {% if institute == department.institute %}

                        <span><h4>{{department.name}}</h4></span>
                        <div class="profile-list lvl3">
                            <ul class="no-bullets">
                            {% for profile in profiles %}
                                {% if department == profile.department %}
                                    <li class="profile-listing"><a href="{{profile.url}}" target="_blank">{{profile.last_name}}, {{profile.first_name}}</a>{% if profile.role %} - {{ profile.role|truncatechars:100 }}{% endif %}</li>
                                {% endif %}
                            {% endfor %}
                            </ul>
                        </div>


                {% endif %}
            {% endfor %}
            </div>
            <hr>
        </div>
    {% endfor %}
    </div>

</div>
{% endblock %}

staff/templates/index.html
{% extends "base.html" %}

{% block content %}
<div id="main" class="container">
    <div id="search">
         <h2>Search</h2>
        <form action="" method="post">
            {% csrf_token %}
            {{ form }}

            <input id="form-submit" type="submit" value="Submit">
        </form>
    </div>
    <hr>

    <div id="loader" style="text-align: center; height: 200px;">
        <img style="width: 200px" src="https://i.pinimg.com/originals/07/24/88/0724884440e8ddd0896ff557b75a222a.gif">
    </div>

    <div id="results">


        {% if results %}
        <h2>{{ keyword }} ...</h2>

            {% if results|length > 1 %}

                {% for result in results %}
                <div class="result">
                    <h3><a href="{{ result.url }}" target="_blank">{{ result.last_name }}, {{ result.first_name }}</a></h3>
                    <h4>{{ result.role }}</h4>
                    <p>{{ result.department }}</p>
                    <p><a href="mailto:{{ result.email }}">{{ result.email }}</a></p>
                    <p class="relevance">Relevance: {{ result.rank|floatformat:0 }}%</p>
                </div>
                {% endfor %}

            {% else %}
                <div id="result">
                    <h4>Your search returned no results.</h4>
                </div>
            {% endif %}
        {% endif %}
    </div>


    <!--
    {% for institute in institutes %}
        <div class="institute-name lvl1">
            <span><h2>{{institute.name}}</h2></span>
            <div class="department-names lvl2">
            {% for department in departments %}
                {% if institute == department.institute %}

                        <span><h3>{{department.name}}</h3></span>
                        <div class="profile-list lvl3">
                            {% for profile in profiles %}
                                {% if department == profile.department %}
                                    <li><a href="{{profile.url}}" target="_blank">{{profile.last_name}}, {{profile.first_name}}</a></li>
                                {% endif %}
                            {% endfor %}
                            </ul>
                        </div>


                {% endif %}
            {% endfor %}
            </div>
        </div>
    {% endfor %}
    -->
</div>
{% endblock %}

staff/templates/keywords.html
{% extends "base.html" %}

{% block content %}
<div id="main" class="container">
    <div id="search">
         <h2>Keywords</h2>
         <p>The list below shows the most common key words shared by all staff profiles in HLS.</p>

    </div>
    <hr>

    <div id="loader" style="text-align: center; height: 200px;">
        <img style="width: 200px" src="https://i.pinimg.com/originals/07/24/88/0724884440e8ddd0896ff557b75a222a.gif">
    </div>


    <div id="results">
        <div>
            <ol>
            {% for keyword in keywords %}
                <li class="keyword"><a href="/search?keyword={{ keyword }}">{{ keyword }}</a></li>
            {% endfor %}
            </ol>
        </div>

    </div>



</div>
{% endblock %}